### ISSUE TITLE
Hostname Support

### ISSUE THREAD

**Issue by tenten8401** [DarkEld3r/os_info#100]
Any chance we could get support for pulling the system hostname with this crate? I feel like it would be a good piece of OS info to have access to.

**Comment by DarkEld3r** [comment]
@tenten8401 Thanks for the suggestion, it is an interesting idea about expanding the crate's functionality, but I suppose having a separate crate for it is a more rusty way.

Have you checked [hostname](https://crates.io/crates/hostname) crate?

**Comment by tenten8401** [comment]
hmm, looks like that isn't maintained but there is gethostname which should work for what I'm looking for.
