### ISSUE TITLE
Windows 10 Version extraction error

### ISSUE THREAD

**Issue by MeFisto94** [DarkEld3r/os_info#110]
So I don't know what the exact issue is, but this should be easy to spot:
Running the example program yields:
```
OS information: WindowsWindows 1010.0.17763
Type: Windows
Version: Windows 1010.0.17763
```
So something is wrong with the version string.

```
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-pc-windows-msvc
release: 1.39.0
LLVM version: 9.0
```

**Comment by MeFisto94** [comment]
Closing as invalid.
I didn't pay proper attention, that this just happens due to the types being concatenated together.
It would help, though, if the example either accessed every element directly or used the debug formatting operator, so people don't stumble over the same issue :)

**Comment by DarkEld3r** [comment]
I'm going to reopen the issue because I think that default formatting should be pretty enough or it is useless. Thanks for raising this issue.
