### ISSUE TITLE
Detect if Windows is 32-bit or 64-bit

### ISSUE THREAD

**Issue by otavio** [DarkEld3r/os_info#117]
On a library we are developing, we'd like to log what the system type it is running. One important information is if it is running on a 32 or 64-bit environment. 

Is there a way to do that now?

**Comment by DarkEld3r** [comment]
`os_info` doesn't provide such functionality, but you can use the `IsWow64Process` function. Do you think it would be useful to have this functionality in this library?

**Comment by otavio** [comment]
It'd be useful for us.

**Comment by DarkEld3r** [comment]
I have implemented it in #119. Could you please check it? I will release a new version if this implementation satisfies your needs.

**Comment by DarkEld3r** [comment]
@otavio I have published 1.3.2 version which includes bitness detection for Linux.

**Comment by otavio** [comment]
Awesome. I'm traveling but will ask for someone at work to give it a go.
