### ISSUE TITLE
winuser feature missing

### ISSUE THREAD

**Issue by okrplay** [DarkEld3r/os_info#122]
Building fails for me, on Windows 10.0.18363, due to `um::winuser` not being available in `winapi`. When adding `winuser` as a feature to winapi, building succeeds. I'm not sure why this isn't happening in CI.

**Comment by DarkEld3r** [comment]
Thank you for the report, it is definitely strange because it works locally for me in addition to CI. Now I see that even more features (for example, `winnt`) are missing.

**Comment by DarkEld3r** [comment]
I have pushed a fix to the master. Could you please check it?

**Comment by DarkEld3r** [comment]
I have published the 1.3.1 version. Please tell if there are any issues.

**Comment by okrplay** [comment]
Thanks, everything's working now 👍
Strange that no one else had this error, as this crate is a dependency of the official mongodb crate.
