### ISSUE TITLE
Windows 10 Strangeness

### ISSUE THREAD

**Issue by Coding-Badly** [DarkEld3r/os_info#127]
Platform: Windows 10 Pro
Rust: stable-x86_64-pc-windows-msvc unchanged - rustc 1.40.0 (73528e339 2019-12-16)
Output from `ver`: `Microsoft Windows [Version 10.0.18362.592]`

Running `cargo run --example print_version` produces...

```
OS information: Windows (Windows 1010.0.18362) (64-bit)
Type: Windows
Version: Windows 1010.0.18362
Bitness: 64-bit
```

Is a space missing from the output?  Does the operating system really report the version as _1010.0.18362_?

**Comment by Coding-Badly** [comment]
I believe there is a space missing here...
https://github.com/DarkEld3r/os_info/blob/master/src/version.rs#L110

I think that should be (space at the end of the quote string)...
`write!(f, "{} ", edition)?;`

**Comment by DarkEld3r** [comment]
You are right, the space is definitely missing there. Thanks!
