### ISSUE TITLE
Make use of serde_derive optional

### ISSUE THREAD

**Issue by Lonami** [DarkEld3r/os_info#137]
Hi, this crate is quite straightforward, but it pulls `serde_derive` (dragging in `syn` and `quote`), which is a dependency users may not need. Perhaps it's a good idea to put this functionality behind a feature flag? E.g., if you install `os_info` with `features = "serde"`, then it will derive them. Otherwise, it won't, and we can save a dependency.

We can of course make it on by default, but this will allow users to disable it if they wish to do so.

**Comment by DarkEld3r** [comment]
Thanks you for the suggestion, it is definitely reasonable.

**Comment by DarkEld3r** [comment]
@Lonami I have published 2.0.0 version which includes this feature.

**Comment by Lonami** [comment]
Thank you, that was fast. Out of curiosity, why was the major version bump necessary? Is this consider a breaking change?

**Comment by DarkEld3r** [comment]
You are right, the `non_exhaustive` is the reason for the breaking change, but there is more of it. SUSE and openSUSE support has been added, so this should be a breaking change even without `non_exhaustive`.
