### ISSUE TITLE
Avoid use of regex crate

### ISSUE THREAD

**Issue by Lonami** [DarkEld3r/os_info#142]
Similar to #137, would it be of interest to remove the `regex` dependency for non-windows systems? I can understand this change would be a bit more intrusive and tougher to maintain, but if this is an acceptable trade-off to have less dependencies, I wouldn't mind sending a PR with the fix.

If this trade-off is not desirable (a bit more complexity and harder to match on new things, but less dependencies), feel free to close, and I won't bother making a PR.

**Comment by DarkEld3r** [comment]
It is an interesting idea. Personally I prefer to add a dependency instead of writing ad-hoc code. At the same time I rarely use regular expressions.

I'm OK with that if you want to remove this dependency.

**Comment by Lonami** [comment]
In my opinion, it is perfectly reasonable to depend on `regex` if there's a considerable use of the crate or complex enough expressions. But, `os_info` is using quite simple regex in very few places, so I feel like it's not strictly needed.

**Comment by DarkEld3r** [comment]
2.0.1 version has been published.
