### ISSUE TITLE
Issues from cli split (broken tests, no license/readme files)

### ISSUE THREAD

**Issue by ignatenkobrain** [DarkEld3r/os_info#165]
```rust
error: couldn't read tests/../../README.md: No such file or directory (os error 2)
 --> tests/md_doc.rs:3:1
  |
3 | doc_comment::doctest!("../../README.md");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Can you make a symlink to the README.md and LICENSE files in each sub-crate so that crates.io tarballs contain those?

Thanks!

**Comment by DarkEld3r** [comment]
Thanks for the report! I'm going to fix this soon.

Though I found it a little bit confusing because crates.io can render the readme (despite of the https://github.com/rust-lang/crates.io/issues/984 issue).

**Comment by DarkEld3r** [comment]
The new version is published.
