### ISSUE TITLE
No matching package named `os_info`

### ISSUE THREAD

**Issue by kawakami-o3** [DarkEld3r/os_info#22]
I encountered the error as follows,
```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching package named `os_info` found (required by `rcc`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.0
```
`rcc` is my project.

`os_type` is not published on crates.io yet?

**Comment by DarkEld3r** [comment]
Thank you for trying to use `os_info`. :smile: You are right: this library hasn't been published on crates.io. I want to polish some more rough edges (#23) before this. Currently it is probably better to use the original crate (`os_type`).

I'm going to use this issue as a reminder for myself to finish the remaining work as soon as possible. :sweat_smile:

**Comment by kawakami-o3** [comment]
Great. I look forward to your update.

I have tried and read `os_type` before your `os_info`, and I have noticed that `os_type` does not work on Windows. Additionally, I like your tactics for detecting an environment.

**Comment by DarkEld3r** [comment]
Finally: https://crates.io/crates/os_info
(Normal) Windows support is still in progress, though.

Feel free to reopen the issue, if something is wrong. :smile:
