### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by DarkEld3r** [DarkEld3r/os_info#3]

**Comment by colindean** [comment]
https://github.com/DarkEld3r/os_info/tree/master/src/windows seems to indicate that Windows support is present now, right?

**Comment by DarkEld3r** [comment]
Not really. 😅 Currently it can only detect Windows OS, but not a concrete version.

**Comment by colindean** [comment]
It looks like your implementation is very similar to if not the same as one proposed on `os_type`: https://github.com/schultyy/os_type/pull/18.

What do you find is still lacking about the implementation as-is?

**Comment by DarkEld3r** [comment]
Thank you, I'm going to look at that. 👍 

On the other hand, I made this crate/fork because I needed a quick working solution and `os_type` seemed a little abandoned at that time. If it becomes actively maintained then perhaps everyone should use it. I'm going to think about it. 🤔

**Comment by mattmccarty** [comment]
I just created a pull request for windows support.

https://github.com/DarkEld3r/os_info/pull/45

**Comment by DarkEld3r** [comment]
Closed by #45.
