### ISSUE TITLE
os_info version 0.1.1 not compiling 

### ISSUE THREAD

**Issue by natboehm** [DarkEld3r/os_info#35]
Hello! I'm currently using your project to try to get the current OS version and name of a given machine however it seems that master has some compilation errors. Upon running `cargo build`, I'm getting the following errors:

```
error[E0271]: type mismatch resolving `<fn() -> version::Version {version::Version::unknown} 
as std::ops::FnOnce<()>>::Output == std::option::Option<std::string::String>`
  --> src/macos/mod.rs:12:57
   |
12 |     let version = retrieve().map(|x| x.product_version).unwrap_or_else(
   |                                                         ^^^^^^^^^^^^^^ expected struct `version::Version`, found enum `std::option::Option`
   |
   = note: expected type `version::Version`
              found type `std::option::Option<std::string::String>`

error[E0308]: mismatched types
  --> src/macos/mod.rs:17:9
   |
17 |         version,
   |         ^^^^^^^ expected struct `version::Version`, found enum `std::option::Option`
   |
   = note: expected type `version::Version`
              found type `std::option::Option<std::string::String>`
   = help: here are some functions which might fulfill your needs:
           - .unwrap()
           - .unwrap_or_default()
```
I looked into them briefly but being unfamiliar with the codebase it was difficult to say where exactly the problem is stemming from.

**Comment by DarkEld3r** [comment]
Thank you for your report. I don't have have OS X at hand right now, so I have to setup Travis build (#38). Please check the `0.2.0` version and let me know if there are more problems.

**Comment by natboehm** [comment]
Version `0.2.0` has a couple compilation errors but version `0.3.0` seems to work. Thanks!
