### ISSUE TITLE
v0.6.0 macos not compiling

### ISSUE THREAD

**Issue by DannyPeck** [DarkEld3r/os_info#50]
The current_platform function within the macos module does not compile in master due to using an Option\<String\> instead of String.

**Comment by DarkEld3r** [comment]
Closed by #51.

**Comment by DarkEld3r** [comment]
@DannyPeck
New version (`0.7.0`) is published, by the way. 😅

**Comment by DannyPeck** [comment]
Thank you!  I appreciate all your help!
