### ISSUE TITLE
On Ubuntu 16.04, it's detected as "16.0"

### ISSUE THREAD

**Issue by mail6543210** [DarkEld3r/os_info#84]
On a ubuntu 16.04 or so, the Version is detected as Custom("16.0").

This is due to the non-greedy match in regex on:
src/linux/lsb_release.rs:54
```
r"Release:\s+([\w]+[.]?[\w]+?)?"
                            ^
```

Removing that `?` solves the problem, but it will break the compatibility.

**Comment by DarkEld3r** [comment]
Thank you for your report, I'm going to try to fix this issue as soon as possible.
